### PR TITLE
Fix nle issues

### PR DESCRIPTION
**Pull request by manuhuth**
to-do:

- return only function value and add the analytical jacobian if new optional argument jac=True.
- move equality test between numerical and analytical jacobian to test_nonlinear_equations.py
- doctests only ensure that they evaluate to zero at a random dimension of the problem
- add some motivating notes to the functions if possible, as for the other modules
- move default values to function header -> tuple
- fix dependencies (numdifftools?)
- fix version issue

### CODE REVIEW

**Comment by manuhuth** [comment]
next:
- CI problem: 'doctests only ensure that they evaluate to zero at a random dimension of the problem' not changed yet -> solve numerically to get roots

**Comment by manuhuth** [comment]
Done here:
-    return only function value and add the analytical jacobian if new optional argument jac=True. - > Done
-    move equality test between numerical and analytical jacobian to test_nonlinear_equations.py - > Done
-    doctests only ensure that they evaluate to zero at a random dimension of the problem -> Done but for some I didn't know the roots and computing them numerically is a bit out of sense if we evaluate it afterwards?
-    move default values to function header -> tuple -> Done

-    add some motivating notes to the functions if possible, as for the other modules -> I need to do this but it is a bit hard for some functions, so I thought we should fix the other issues first.

- fix dependencies (numdifftools?) -> done in your request?
- fix version issue -> done in your request?

**Review by amageh — APPROVED** [review]
Hi @manuhuth ! Everything looks good to me! I added my commits for the release.

One minor thing: please add the `jac` argument to the docstrings. Also, I didn't pay attention to this when we discussed these changes but I think calling the argument `return_jac` would be even better since that makes the True/False inputs more intuitive there. Feel free to stick with `jac` though if you prefer that.

Not sure about the doctests, maybe Philipp can weigh in.

**Comment by manuhuth** [comment]
@amageh thanks! I fixed the issues. I would prefer to stick to jac. I think this more common but definetly see your point! :)
I have asked Philipp about the doctests and will merge afterwards.

**Pull request merged**
